decode is throwing an attribute error
Determine what is causing the exception by encapsulating cmplx in a try-except block.
```
Traceback (most recent call last):
  File "test.py", line 82, in test_clean
    analytics.default_client._clean(combined)
  File "/home/travis/build/duly/analytics-python/analytics/client.py", line 203, in _clean
    return self._clean_dict(item)
  File "/home/travis/build/duly/analytics-python/analytics/client.py", line 189, in _clean_dict
    data[k] = self._clean(v)
  File "/home/travis/build/duly/analytics-python/analytics/client.py", line 205, in _clean
    return self._coerce_unicode(item)
  File "/home/travis/build/duly/analytics-python/analytics/client.py", line 180, in _coerce_unicode
    return cmplx.decode("utf-8", "strict")
AttributeError: 'exceptions.Exception' object has no attribute 'decode'
```