decode instead of unicode() for unicode handling
http://docs.python.org/2/howto/unicode.html
http://docs.python.org/release/3.0.1/howto/unicode.html
```
Traceback (most recent call last):
  File "test.py", line 82, in test_clean
    analytics.default_client._clean(combined)
  File "/home/travis/build/duly/analytics-python/analytics/client.py", line 203, in _clean
    return self._clean_dict(item)
  File "/home/travis/build/duly/analytics-python/analytics/client.py", line 189, in _clean_dict
    data[k] = self._clean(v)
  File "/home/travis/build/duly/analytics-python/analytics/client.py", line 205, in _clean
    return self._coerce_unicode(item)
  File "/home/travis/build/duly/analytics-python/analytics/client.py", line 180, in _coerce_unicode
    return six.u(cmplx)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/six.py", line 528, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
AttributeError: 'exceptions.Exception' object has no attribute 'replace'
```