Run decode on an Exception's args
Since the key is exception and the value is an Exception. Run decode on the Exception arguments as opposed to the Exception itself which does not contain a 'decode' attribute.
```
python/analytics/client.py", line 209, in _clean
    return self._coerce_unicode(item)
  File "/home/travis/build/duly/analytics-python/analytics/client.py", line 181, in _coerce_unicode
    item = cmplx.decode("utf-8", "strict")
AttributeError: 'exceptions.Exception' object has no attribute 'decode'
```